export const RoutesConfig = {
    adminUrl: 'admin',
    login: 'login',
    users: 'users',
    adminUsers: 'admin/users',
    adminAdministrators : 'admin/administrators',
    adminLotteries: 'admin/lotteries',
    adminQuizzes: 'admin/quizzes',
    adminSpecialQuizzes: 'admin/special-quizzes',
    adminGames: 'admin/games',
    adminOrders: 'admin/orders',
    adminPresents: 'admin/presents',
    adminSettings: 'admin/settings',
    adminChats: 'admin/chats',
    adminReports: 'admin/reports',
    adminLogs: 'admin/logs',
    adminQuests: 'admin/quests',
};
